
let products=[], editImage="";
async function api(url,opt={}){let r=await fetch(url,opt);let d=await r.json();if(!r.ok)throw new Error(d.error||"خطا");return d}
async function check(){let d=await api("/api/admin/me");if(d.loggedIn)showPanel()}
function showPanel(){document.getElementById("loginBox").hidden=true;document.getElementById("panel").hidden=false;load()}
async function login(){try{await api("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:document.getElementById("password").value})});showPanel()}catch(e){document.getElementById("loginMsg").textContent=e.message;document.getElementById("loginMsg").className="msg"}}
async function logout(){await api("/api/admin/logout",{method:"POST"});location.reload()}
async function load(){products=await api("/api/products");render();loadOrders()}
function render(){document.getElementById("adminProducts").innerHTML=products.length?products.map(p=>`<div class="adminItem"><div>${p.image?`<img src="${p.image}">`:"✦"}</div><div class="grow"><b>${esc(p.name)}</b><div class="muted">${money(p.price)}</div><div class="muted">${esc(p.description||"")}</div></div><button class="ghost" onclick='edit(${JSON.stringify(p)})'>ویرایش</button><button class="danger" onclick="del('${p.id}')">حذف</button></div>`).join(""):"<p class='muted'>هنوز محصولی اضافه نشده.</p>"}
function edit(p){document.getElementById("editId").value=p.id;document.getElementById("name").value=p.name;document.getElementById("price").value=p.price;document.getElementById("description").value=p.description;editImage=p.image||"";document.getElementById("formTitle").textContent="ویرایش محصول";document.getElementById("preview").innerHTML=editImage?`<img src="${editImage}" style="max-width:180px;border-radius:10px">`:"";scrollTo({top:0,behavior:"smooth"})}
function resetForm(){["name","price","description","editId"].forEach(id=>document.getElementById(id).value="");editImage="";document.getElementById("preview").innerHTML="";document.getElementById("formTitle").textContent="افزودن محصول"}
async function uploadImage(){let f=document.getElementById("imageFile").files[0];if(!f)return;let data=await new Promise((ok,no)=>{let r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});try{let d=await api("/api/admin/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mime:f.type,data})});editImage=d.url;document.getElementById("preview").innerHTML=`<img src="${editImage}" style="max-width:180px;border-radius:10px">`}catch(e){alert(e.message)}}
async function saveProduct(){let body={name:document.getElementById("name").value,price:Number(document.getElementById("price").value),description:document.getElementById("description").value,image:editImage};try{let id=document.getElementById("editId").value;if(id)await api("/api/admin/products/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});else await api("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});resetForm();load()}catch(e){alert(e.message)}}
async function del(id){if(!confirm("این محصول حذف شود؟"))return;try{await api("/api/admin/products/"+id,{method:"DELETE"});load()}catch(e){alert(e.message)}}
async function loadOrders(){try{let o=await api("/api/admin/orders");document.getElementById("orders").innerHTML=o.length?o.map(x=>`<div class="order"><b>سفارش ${x.id.slice(0,8)}</b> — ${money(x.total)}<div class="muted">${new Date(x.createdAt).toLocaleString("fa-IR")}</div>${x.items.map(i=>`<div>${esc(i.name)} × ${i.qty}</div>`).join("")}</div>`).join(""):"<p class='muted'>سفارشی ثبت نشده.</p>"}catch(e){}}
const money=n=>new Intl.NumberFormat("fa-IR").format(n)+" تومان";const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));check();
