const $=s=>document.querySelector(s);
let products=[],videos=[],cart=JSON.parse(localStorage.getItem("blackgun_cart")||"[]");
async function load(){try{const [a,b]=await Promise.all([fetch("/api/products"),fetch("/api/videos")]);products=await a.json();videos=await b.json();renderProducts();renderVideos();renderCart()}catch(e){console.error(e)}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function renderProducts(list=products){$("#productsGrid").innerHTML=list.map(p=>`<article class="card"><img src="${esc(p.image||"")}" alt=""><div class="cardBody"><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="price">${Number(p.price||0).toLocaleString()} تومان</div><button onclick="add(${p.id})">افزودن به سبد</button></div></article>`).join("")||"<p>محصولی ثبت نشده است.</p>"}
function renderVideos(){$("#videosGrid").innerHTML=videos.map(v=>`<div class="video"><h3>${esc(v.title)}</h3><iframe src="${esc(v.url)}" allowfullscreen></iframe><p>${esc(v.description)}</p></div>`).join("")||"<p>هنوز ویدیویی اضافه نشده است.</p>"}
function add(id){const p=products.find(x=>x.id==id);if(!p)return;const x=cart.find(x=>x.id==id);x?x.qty++:cart.push({id:p.id,name:p.name,price:Number(p.price)||0,image:p.image,qty:1});save();toast("محصول به سبد اضافه شد")}
function chg(id,n){const x=cart.find(x=>x.id==id);if(!x)return;x.qty+=n;cart=cart.filter(x=>x.qty>0);save()}
function save(){localStorage.setItem("blackgun_cart",JSON.stringify(cart));renderCart()}
function renderCart(){let total=0;$("#cartItems").innerHTML=cart.map(x=>{total+=x.price*x.qty;return `<div class="cartItem"><img src="${esc(x.image||"")}"><div><b>${esc(x.name)}</b><div>${x.price.toLocaleString()} تومان</div><div class="qty"><button onclick="chg(${x.id},-1)">−</button> ${x.qty} <button onclick="chg(${x.id},1)">+</button></div></div><button onclick="chg(${x.id},-${x.qty})">حذف</button></div>`}).join("")||"<p>سبد خرید خالی است.</p>";$("#cartTotal").textContent=total.toLocaleString();$("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0)}
function toast(t){$("#toast").textContent=t;$("#toast").style.display="block";setTimeout(()=>$("#toast").style.display="none",1800)}
$("#cartBtn").onclick=()=>$("#cart").classList.add("open");$("#closeCart").onclick=()=>$("#cart").classList.remove("open");$("#search").oninput=e=>renderProducts(products.filter(p=>(p.name+" "+p.description).toLowerCase().includes(e.target.value.toLowerCase())));load();