const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');const {URL}=require('url');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'1236';
const SB=String(process.env.SUPABASE_URL||'').replace(/\/+$/,''),KEY=String(process.env.SUPABASE_SECRET_KEY||'').trim(),sessions=new Set();
const j=(r,s,d,x={})=>(r.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...x}),r.end(JSON.stringify(d)));
const body=q=>new Promise((ok,no)=>{let a=[];q.on('data',x=>a.push(x));q.on('end',()=>ok(Buffer.concat(a)));q.on('error',no)});
async function jb(q){let b=await body(q);try{return b.length?JSON.parse(b):{}}catch{return{}}} function ck(q){let o={};(q.headers.cookie||'').split(';').forEach(x=>{let i=x.indexOf('=');if(i>0)o[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())});return o}
function admin(q){return sessions.has(ck(q).admin_session)}function need(q,r){if(!admin(q)){j(r,401,{error:'Unauthorized'});return false}return true}
async function sb(ep,opt={}){if(!SB||!KEY)throw Error('Supabase environment variables are missing');let r=await fetch(SB+ep,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,...(opt.headers||{})}}),t=await r.text(),d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.error||t||'Supabase error');return d}
const mp=p=>({id:String(p.id),name:p.name||'',price:Number(p.price||0),image:p.image||'',description:p.description||'',createdAt:p.created_at});
const mv=v=>({id:String(v.id),title:v.title||'',url:v.url||'',description:v.description||'',createdAt:v.created_at});
async function products(){return(await sb('/rest/v1/products?select=*&order=created_at.desc')).map(mp)}async function videos(){return(await sb('/rest/v1/videos?select=*&order=created_at.desc')).map(mv)}
async function addP(d){let x={name:String(d.name||'').trim(),price:Math.round(Number(d.price||0)),image:String(d.image||'').trim(),description:String(d.description||'').trim()};if(!x.name)throw Error('نام محصول الزامی است');let r=await sb('/rest/v1/products',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(x)});return mp(r[0])}
async function editP(id,d){let x=await addSafe(d),r=await sb(`/rest/v1/products?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(x)});return mp(r[0])}async function addSafe(d){return{name:String(d.name||'').trim(),price:Math.round(Number(d.price||0)),image:String(d.image||'').trim(),description:String(d.description||'').trim()}}
async function order(d){let x={customer_name:String(d.name||''),phone:String(d.phone||''),address:String(d.address||''),items:Array.isArray(d.items)?d.items:[],total:Number(d.total||0),status:'new'},r=await sb('/rest/v1/orders',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(x)});return r[0]}
function file(p){try{p=decodeURIComponent(p)}catch{return null}if(p==='/')p='/index.html';let root=path.resolve(ROOT),f=path.resolve(ROOT,p.replace(/^[/\\]+/,''));return f.startsWith(root+path.sep)?f:null}function mime(f){return({'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.mp4':'video/mp4','.webm':'video/webm'})[path.extname(f).toLowerCase()]||'application/octet-stream'}
async function go(q,r){let u=new URL(q.url,`http://${q.headers.host||'localhost'}`),p=u.pathname;try{
if(p==='/api/products'&&q.method==='GET')return j(r,200,await products());if(p==='/api/videos'&&q.method==='GET')return j(r,200,await videos());
if(p==='/api/admin/login'&&q.method==='POST'){let d=await jb(q);if(String(d.password)!==ADMIN_PASSWORD)return j(r,401,{error:'رمز اشتباه است'});let t=crypto.randomBytes(32).toString('hex');sessions.add(t);return j(r,200,{ok:true},{'Set-Cookie':`admin_session=${t}; HttpOnly; Path=/; SameSite=Lax; Max-Age=86400`})}
if(p==='/api/admin/logout'&&q.method==='POST'){sessions.delete(ck(q).admin_session||'');return j(r,200,{ok:true},{'Set-Cookie':'admin_session=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax'})}if(p==='/api/admin/check')return j(r,200,{ok:admin(q)});
if(p==='/api/admin/products'&&q.method==='GET'){if(!need(q,r))return;j(r,200,await products())}if(p==='/api/admin/products'&&q.method==='POST'){if(!need(q,r))return;j(r,201,{product:await addP(await jb(q))})}if(p.startsWith('/api/admin/products/')&&q.method==='PUT'){if(!need(q,r))return;j(r,200,{product:await editP(p.split('/').pop(),await jb(q))})}if(p.startsWith('/api/admin/products/')&&q.method==='DELETE'){if(!need(q,r))return;await sb(`/rest/v1/products?id=eq.${encodeURIComponent(p.split('/').pop())}`,{method:'DELETE'});return j(r,200,{ok:true})}
if(p==='/api/admin/videos'&&q.method==='GET'){if(!need(q,r))return;j(r,200,await videos())}if(p==='/api/admin/videos'&&q.method==='POST'){if(!need(q,r))return;let d=await jb(q),v=await sb('/rest/v1/videos',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({title:String(d.title||'').trim(),url:String(d.url||'').trim(),description:String(d.description||'').trim()})});return j(r,201,{video:mv(v[0])})}if(p.startsWith('/api/admin/videos/')&&q.method==='DELETE'){if(!need(q,r))return;await sb(`/rest/v1/videos?id=eq.${encodeURIComponent(p.split('/').pop())}`,{method:'DELETE'});return j(r,200,{ok:true})}
if(p==='/api/orders'&&q.method==='POST')return j(r,201,{ok:true,order:await order(await jb(q))});if(p==='/api/admin/orders'&&q.method==='GET'){if(!need(q,r))return;j(r,200,await sb('/rest/v1/orders?select=*&order=created_at.desc'))}
let f=file(p);if(f&&fs.existsSync(f)&&fs.statSync(f).isFile()){r.writeHead(200,{'Content-Type':mime(f),'Cache-Control':'public,max-age=3600'});return fs.createReadStream(f).pipe(r)}return j(r,404,{error:'Not found'})}catch(e){console.error(e);return j(r,500,{error:e.message||'Server error'})}}
http.createServer(go).listen(PORT,'0.0.0.0',()=>console.log(`Shop Black running on ${PORT}`));
