const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");const {URL}=require("url");
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,PUBLIC=ROOT,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"1236";
const SUPABASE_URL=String(process.env.SUPABASE_URL||"").replace(/\/+$/,""),SUPABASE_SECRET_KEY=String(process.env.SUPABASE_SECRET_KEY||"");
const ORDERS=path.join(ROOT,"orders.json"),sessions=new Set();if(!fs.existsSync(ORDERS))fs.writeFileSync(ORDERS,"[]");
function json(res,s,d,x={}){res.writeHead(s,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...x});res.end(JSON.stringify(d))}
function read(f){try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return[]}}function write(f,d){fs.writeFileSync(f,JSON.stringify(d,null,2))}
function cookies(req){const o={};(req.headers.cookie||"").split(";").forEach(x=>{const i=x.indexOf("=");if(i>=0)o[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())});return o}
function isAdmin(req){const t=cookies(req).admin_session;return!!t&&sessions.has(t)}function need(req,res){if(!isAdmin(req)){json(res,401,{ok:false,error:"Unauthorized"});return false}return true}
function body(req){return new Promise((ok,no)=>{const a=[];req.on("data",x=>a.push(x));req.on("end",()=>ok(Buffer.concat(a)));req.on("error",no)})}
async function jbody(req){const b=await body(req);try{return b.length?JSON.parse(b):{}}catch{return{}}}
async function sb(ep,opt={}){if(!SUPABASE_URL||!SUPABASE_SECRET_KEY)throw Error("Supabase environment variables are missing");const r=await fetch(SUPABASE_URL+ep,{...opt,headers:{apikey:SUPABASE_SECRET_KEY,Authorization:`Bearer ${SUPABASE_SECRET_KEY}`,...(opt.headers||{})}}),t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(typeof d==="string"?d:d?.message||d?.error||"Supabase error");return d}
function map(p){return{id:String(p.id),name:p.name||"",price:Number(p.price||0),image:p.image||"",description:p.description||"",createdAt:p.created_at||null}}
async function products(){return(await sb("/rest/v1/products?select=*&order=created_at.desc")).map(map)}
async function add(d){const r=await sb("/rest/v1/products",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({name:String(d.name||"").trim(),price:Math.round(Number(d.price||0)),image:String(d.image||"").trim(),description:String(d.description||"").trim()})});return map(r[0])}
async function edit(id,d){const r=await sb(`/rest/v1/products?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({name:String(d.name||"").trim(),price:Math.round(Number(d.price||0)),image:String(d.image||"").trim(),description:String(d.description||"").trim()})});if(!r.length)throw Error("Product not found");return map(r[0])}
async function del(id){await sb(`/rest/v1/products?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"})}
async function bucket(){try{await sb("/storage/v1/bucket/product-images");return}catch{}try{await sb("/storage/v1/bucket",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:"product-images",name:"product-images",public:true})})}catch{}}
function multipart(b,ct){const m=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/i);if(!m)throw Error("Multipart boundary not found");const ps=b.toString("latin1").split("--"+(m[1]||m[2])),o=[];for(const p of ps){const i=p.indexOf("\r\n\r\n");if(i<0)continue;const h=p.slice(0,i);let c=p.slice(i+4);if(c.endsWith("\r\n"))c=c.slice(0,-2);const n=h.match(/name="([^"]+)"/i),f=h.match(/filename="([^"]*)"/i),t=h.match(/Content-Type:\s*([^\r\n]+)/i);if(n)o.push({name:n[1],filename:f?f[1]:null,contentType:t?t[1].trim():"application/octet-stream",data:Buffer.from(c,"latin1")})}return o}
async function upload(f){await bucket();const ext=path.extname(f.filename||"").toLowerCase()||".jpg",name=`${Date.now()}-${crypto.randomBytes(6).toString("hex")}${ext}`;await sb(`/storage/v1/object/product-images/${encodeURIComponent(name)}`,{method:"POST",headers:{"Content-Type":f.contentType,"x-upsert":"true"},body:f.data});return `${SUPABASE_URL}/storage/v1/object/public/product-images/${name}`}
function mime(f){return({".html":"text/html; charset=utf-8",".js":"application/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".gif":"image/gif",".svg":"image/svg+xml",".mp4":"video/mp4",".webm":"video/webm"})[path.extname(f).toLowerCase()]||"application/octet-stream"}
function safe(p){let d;try{d=decodeURIComponent(p)}catch{return null}if(d==="/")d="/index.html";const r=path.resolve(PUBLIC),f=path.resolve(PUBLIC,d.replace(/^[/\\]+/,""));return f!==r&&!f.startsWith(r+path.sep)?null:f}
async function handle(req,res){const u=new URL(req.url,`http://${req.headers.host||"localhost"}`),p=u.pathname;try{
if(p==="/api/products"&&req.method==="GET")return json(res,200,await products());
if(p==="/api/admin/login"&&req.method==="POST"){const d=await jbody(req);if(String(d.password||"")!==ADMIN_PASSWORD)return json(res,401,{ok:false,error:"رمز عبور اشتباه است"});const t=crypto.randomBytes(32).toString("hex");sessions.add(t);return json(res,200,{ok:true},{"Set-Cookie":`admin_session=${t}; HttpOnly; Path=/; SameSite=Lax`})}
if(p==="/api/admin/logout"&&req.method==="POST"){const t=cookies(req).admin_session;if(t)sessions.delete(t);return json(res,200,{ok:true},{"Set-Cookie":"admin_session=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax"})}
if(p==="/api/admin/check"&&req.method==="GET")return json(res,200,{ok:isAdmin(req)});
if(p==="/api/admin/products"&&req.method==="GET"){if(!need(req,res))return;return json(res,200,await products())}
if(p==="/api/admin/products"&&req.method==="POST"){if(!need(req,res))return;const d=await jbody(req);if(!String(d.name||"").trim())return json(res,400,{ok:false,error:"نام محصول وارد نشده"});return json(res,201,{ok:true,product:await add(d)})}
if(p.startsWith("/api/admin/products/")&&req.method==="PUT"){if(!need(req,res))return;return json(res,200,{ok:true,product:await edit(p.split("/").pop(),await jbody(req))})}
if(p.startsWith("/api/admin/products/")&&req.method==="DELETE"){if(!need(req,res))return;await del(p.split("/").pop());return json(res,200,{ok:true})}
if(p==="/api/admin/upload"&&req.method==="POST"){if(!need(req,res))return;const ct=req.headers["content-type"]||"";if(!ct.toLowerCase().startsWith("multipart/form-data"))return json(res,400,{ok:false,error:"فایل ارسال نشده"});const f=multipart(await body(req),ct).find(x=>x.filename);if(!f)return json(res,400,{ok:false,error:"فایل پیدا نشد"});const image=await upload(f);return json(res,200,{ok:true,url:image,image})}
if(p==="/api/orders"&&req.method==="POST"){const d=await jbody(req),a=read(ORDERS),o={id:Date.now().toString()+crypto.randomBytes(3).toString("hex"),createdAt:new Date().toISOString(),name:d.name||"",phone:d.phone||"",address:d.address||"",items:Array.isArray(d.items)?d.items:[],total:Number(d.total||0),status:"new"};a.unshift(o);write(ORDERS,a);return json(res,201,{ok:true,order:o})}
if(p==="/api/admin/orders"&&req.method==="GET"){if(!need(req,res))return;return json(res,200,read(ORDERS))}
const f=safe(p);if(f&&fs.existsSync(f)&&fs.statSync(f).isFile()){res.writeHead(200,{"Content-Type":mime(f),"Cache-Control":"public, max-age=3600"});return fs.createReadStream(f).pipe(res)}const i=path.join(PUBLIC,"index.html");if(fs.existsSync(i)){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});return fs.createReadStream(i).pipe(res)}return json(res,404,{ok:false,error:"Not found"})
}catch(e){console.error(e);return json(res,500,{ok:false,error:e.message||"Server error"})}}
http.createServer(handle).listen(PORT,"0.0.0.0",()=>console.log(`Shop Black running on port ${PORT}`));
